import glob
from configparser import ConfigParser
import os
from telethon import TelegramClient
config = ConfigParser()
config.read('Config.cfg')
api_id = int(config['telegram']['api_id'])
api_hash = config['telegram']['api_hash']
print("______________¶¶¶")
print("_____________¶¶_¶¶¶¶")
print("____________¶¶____¶¶¶")
print("___________¶¶¶______¶¶")
print("___________¶¶¶_______¶¶")
print("__________¶¶¶¶________¶¶")
print("__________¶_¶¶_________¶¶")
print("__________¶__¶¶_________¶¶____¶¶")
print("__________¶__¶¶__________¶¶¶¶¶¶¶")
print("_________¶¶__¶¶¶______¶¶¶¶¶¶___¶")
print("_________¶¶___¶¶__¶¶¶¶¶¶__¶¶")
print("_______¶¶_¶____¶¶¶¶________¶¶")
print("______¶¶__¶¶___¶¶__________¶¶")
print("_____¶¶____¶¶___¶¶__________¶¶")
print("___¶¶_______¶¶___¶¶_________¶¶")
print("___¶¶¶¶¶¶¶¶¶¶¶¶¶__¶¶_________¶")
print("_¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶_¶¶________¶¶")
print("¶¶__¶¶¶¶¶¶____¶¶¶¶¶¶¶¶¶______¶¶")
print("¶¶¶¶¶___¶______¶___¶¶¶¶¶_____¶¶")
print("________¶¶¶¶¶¶¶¶______¶¶¶¶¶_¶¶")
print("______¶¶¶¶¶¶¶¶¶¶¶________¶¶¶¶")
print("______¶¶¶¶¶¶¶¶¶¶¶¶")
print("______¶__¶¶_¶¶¶¶¶¶")
print("_____¶¶______¶___¶      Simple Telegram Spamming Client")
print("_____¶¶_____¶¶___¶")
print("_____¶______¶¶___¶      Don't use too often, it can lead to limiting your account")
print("____¶¶______¶¶___¶¶     To get started:")
print("____¶¶______¶¶___¶¶     1. Replace pictures in jpg / png format in the Pictures folder")
print("___¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶     2. Go to https://my.telegram.org and create Application")
print("__¶¶¶¶¶¶¶¶¶_¶¶¶¶¶¶¶¶    3. Copy api_id and api_hash into config.cfg")
print("__¶¶________¶¶¶____¶¶   4. Run script and create session")
print("____¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶")
print("Using API_ID "+ str(api_id))
print("Using API_HASH "+api_hash)
client = TelegramClient('session_name', api_id, api_hash)
async def initialspam():
    bot_name = input("Enter Bot Name without using @. Example: armyrusBOT\n")
    await client.send_message(bot_name, '/start')
    for jpgfile in glob.iglob(os.path.join("Pictures", "*.jpg")):
        print("Sending " + jpgfile)
        await client.send_file(bot_name, jpgfile)
    for pngfile in glob.iglob(os.path.join("Pictures", "*.png")):
        print("Sending " + pngfile)
        await client.send_file(bot_name, pngfile)
    print("Done")
    input("Press Enter to choose another target")
    await initialspam()
with client:
    client.loop.run_until_complete(initialspam())
async def main():
    await initialspam()